// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import CookiesController from "./cookies_controller"
application.register("cookies", CookiesController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)
